### ISSUE TITLE
Tutorial 1, Activity 2 solution?

### ISSUE THREAD

**Issue by steve-kasica** [UBC-InfoVis/2021-436V-tutorials#1]
@michael-oppermann do you have a solution for [Activity (2) in the first D3 tutorial](https://github.com/UBC-InfoVis/2021-436V-tutorials/tree/master/1_D3_Tutorial#activity-2)? Some students are asking for it.

**Comment by michael-oppermann** [comment]
Added exampled to _2021-436V-examples_
https://github.com/UBC-InfoVis/2021-436V-examples/tree/master/d3-bind-data-to-elements
https://githubbox.com/UBC-InfoVis/2021-436V-examples/tree/master/d3-bind-data-to-elements
